[versions]
activityCompose = "1.7.2"
androidGradlePlugin = "8.1.1"
androidVideoTrimmer = "0.1.5-async"
appcompat = "1.6.1"
composeUiVersion = "1.6.0-alpha05"
constraintlayout = "2.1.4"
coordinatorlayout = "1.2.0"
coreKtx = "1.12.0"
datastore = "1.0.0"
espresso = "3.5.1"
exoplayer = "2.19.1"
extendedspans = "1.3.0"
firebaseBom = "32.2.3"
firebaseAuth = "22.1.1"
glide = "4.15.1"
glideCompose = "1.0.0-alpha.1"
googleServices = "4.3.15"
hiltCompose = "1.1.0-alpha01"
junitExt = "1.1.5"
junit = "4.13.2"
keyboard-visibility-event = "v3.0.0-RC3"
kotlin = "1.9.10"
kotlinGradlePlugin = "1.9.10"
ksp = "1.9.10-1.0.13"
lifecycleRuntimeCompose = "2.6.2"
lifecycleRuntimeKtx = "2.6.2"
lifecycleViewmodelCompose = "2.6.2"
lifecycleViewmodelKtx = "2.7.0-alpha02"
lottie = "6.1.0"
hilt = "2.48"
androidxComposeBom = "2023.09.00"
androidxComposeMaterial = "1.6.0-alpha05"
androidxComposeMaterial3 = "1.2.0-alpha07"
material = "1.9.0"
media3 = "1.2.0-alpha01"
mobileFfmpegMinGpl = "4.4"
mockito = "2.21.0"
navigationKtx = "2.7.2"
navigationSafeArgsGradlePlugin = "2.7.2"
paging = "3.2.1"
playServicesAuth = "20.7.0"
room = "2.5.2"

[libraries]
android-video-trimmer = { group = "com.github.TTC1018", name = "android-video-trimmer", version.ref = "androidVideoTrimmer" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxComposeMaterial" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata"}
android-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
android-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCompose" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompose" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationKtx" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
exoplayer = { group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "exoplayer" }
extendedspans = { group = "me.saket.extendedspans", name = "extendedspans", version.ref = "extendedspans" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideCompose" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
keyboard-visibility-event = { group = "com.github.yshrsmz", name = "KeyboardVisibilityEvent", version.ref = "keyboard-visibility-event" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mobile-ffmpeg-min-gpl = { group = "com.arthenica", name = "mobile-ffmpeg-min-gpl", version.ref = "mobileFfmpegMinGpl" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
androidx-navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationSafeArgsGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]

